package project.usables;

import java.net.MalformedURLException;
import java.net.URL;

/**
 * A util class used to call upon certain resources generated by this program.
 * 
 * It is up for deprecation as it is being replaced with {@link project.constants.ResourceDistributor}
 */
public class ResourceGrabber {
  private ResourceGrabber() {}
  
  /** 
   * @return URL
   */
  public static URL getDefaultCoverArt() {
    try {
    return ResourceGrabber.class.getClass().getResource("resource/icons/others/disk.png");
    } catch (NullPointerException e) {
      try {
        return new URL("resource/icons/others/disk.png");
      } catch (MalformedURLException e1) {
        e1.printStackTrace();
      }
    }
    return null;
  }
}
