/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_connection_Bridge */
#include <iostream>
using namespace std;
#ifndef _Included_project_connection_Bridge
#define _Included_project_connection_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     project_connection_Bridge
 * Method:    cliPrint
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_project_connection_Bridge_cliPrint
  (JNIEnv *, jobject, jstring) {
    cout << jstring << endl;
  }

#ifdef __cplusplus
}
#endif
#endif
